/* seq - drop&create  */
DROP SEQUENCE DIARYROOT_FOLDERNOSEQ;
DROP SEQUENCE DIARYROOT_FOLDERSEQ;
DROP SEQUENCE JUKESEQ;
DROP SEQUENCE DIARY_DIARYNOSEQ;
DROP SEQUENCE DIARY_GROUPNOSEQ;
DROP SEQUENCE RELATIONSEQ;
DROP SEQUENCE FRIENDSEQ;
DROP SEQUENCE CHATSEQ;

CREATE SEQUENCE DIARYROOT_FOLDERNOSEQ;
CREATE SEQUENCE DIARYROOT_FOLDERSEQ;
CREATE SEQUENCE DIARY_DIARYNOSEQ;
CREATE SEQUENCE DIARY_GROUPNOSEQ;
CREATE SEQUENCE JUKESEQ;
CREATE SEQUENCE RELATIONSEQ;
CREATE SEQUENCE FRIENDSEQ;
CREATE SEQUENCE CHATSEQ;

/*DROP TABLE*/
DROP TABLE HOMEINFO;
DROP TABLE CHATCREATE;
DROP TABLE CHATROOM;
DROP TABLE FRIENDCREATE;
DROP TABLE CHAT;
DROP TABLE VISIT;
DROP TABLE MUSIC;
DROP TABLE DIARY;
DROP TABLE DIARYROOT;
DROP TABLE USERINFO;
DROP TABLE RELATIONSHIP;

CREATE TABLE USERINFO (
	email	varchar2(100)	NOT NULL,
	password	varchar2(100)	NULL,
	gender	varchar2(1)	NULL,
	joindate	date	NULL,
	birthdate	date	NULL,
	username	varchar2(100)	NULL,
	visitdate	date	NULL,
	pwdate	date	NULL,
	addr	varchar2(500)	NULL,
	coinno	number	NULL,
	usercondition	number	NULL
);

CREATE TABLE DIARY (
	diaryno	number	NOT NULL,
	folderno	number	NOT NULL,
	email	varchar2(100)	NOT NULL,
	title	varchar2(1000)	NULL,
	content	varchar2(3000)	NULL,
	regdate	date	NULL,
	fileurl	varchar2(3000)	NULL,
	picurl	varchar2(3000)	NULL,
	mapname	varchar2(1000)	NULL,
	maplati	number	NULL,
	maplong	number	NULL,
	videourl	varchar2(3000)	NULL,
	groupno	number	NULL,
	groupsq	number	NULL
);

CREATE TABLE MUSIC (
	musicno	number	NOT NULL,
	email	varchar2(100)	NOT NULL,
	singer	varchar2(500)	NULL,
	musictitle	varchar2(500)	NULL,
	runtime	varchar2(100)	NULL,
	musicalbum	varchar2(500)	NULL,
	background	varchar2(1)	NOT NULL
);

CREATE TABLE VISIT (
	email	varchar2(100)	NOT NULL,
	v_email	varchar2(100)	NOT NULL,
	v_date	date	NOT NULL
);

CREATE TABLE CHAT (
	chatno	number	NOT NULL,
	relationno	number	NOT NULL,
	email	varchar2(100)	NOT NULL,
	chattext	varchar2(500)	NULL,
	chatdate	date	NULL
);

CREATE TABLE FRIENDCREATE (
	friendcreno	number	NOT NULL,
	email	varchar2(100)	NOT NULL,
	relationno	number	NOT NULL
);

CREATE TABLE DIARYROOT (
	folderno	number	NOT NULL,
	email	varchar2(100)	NOT NULL,
	foldername	varchar2(100)	NULL,
	foldersq	number	NULL
);

CREATE TABLE HOMEINFO (
	email	varchar2(100)	NOT NULL,
	p_picurl	varchar2(500)	NOT NULL,
	p_content	varchar2(500)	NULL,
	p_title	varchar2(500)	NULL
);

CREATE TABLE RELATIONSHIP (
	relationno	number	NOT NULL
);

ALTER TABLE USERINFO ADD CONSTRAINT PK_USERINFO PRIMARY KEY (
	email
);

ALTER TABLE DIARY ADD CONSTRAINT PK_DIARY PRIMARY KEY (
	diaryno,
	folderno,
	email
);

ALTER TABLE MUSIC ADD CONSTRAINT PK_MUSIC PRIMARY KEY (
	musicno,
	email
);

ALTER TABLE VISIT ADD CONSTRAINT PK_VISIT PRIMARY KEY (
	email
);

ALTER TABLE CHAT ADD CONSTRAINT PK_CHAT PRIMARY KEY (
	chatno,
	relationno,
	email
);

ALTER TABLE FRIENDCREATE ADD CONSTRAINT PK_FRIENDCREATE PRIMARY KEY (
	friendcreno,
	email,
	relationno
);

ALTER TABLE DIARYROOT ADD CONSTRAINT PK_DIARYROOT PRIMARY KEY (
	folderno
);

ALTER TABLE HOMEINFO ADD CONSTRAINT PK_HOMEINFO PRIMARY KEY (
	email
);

ALTER TABLE RELATIONSHIP ADD CONSTRAINT PK_RELATIONSHIP PRIMARY KEY (
	relationno
);

ALTER TABLE DIARY ADD CONSTRAINT FK_DIARYROOT_TO_DIARY_1 FOREIGN KEY (
	folderno
)
REFERENCES DIARYROOT (
	folderno
) ON DELETE CASCADE ENABLE;

ALTER TABLE DIARY ADD CONSTRAINT FK_USERINFO_TO_DIARY_1 FOREIGN KEY (
	email
)
REFERENCES USERINFO (
	email
);

ALTER TABLE MUSIC ADD CONSTRAINT FK_USERINFO_TO_MUSIC_1 FOREIGN KEY (
	email
)
REFERENCES USERINFO (
	email
);

ALTER TABLE VISIT ADD CONSTRAINT FK_USERINFO_TO_VISIT_1 FOREIGN KEY (
	email
)
REFERENCES USERINFO (
	email
);

ALTER TABLE CHAT ADD CONSTRAINT FK_RELATIONSHIP_TO_CHAT_1 FOREIGN KEY (
	relationno
)
REFERENCES RELATIONSHIP (
	relationno
);

ALTER TABLE CHAT ADD CONSTRAINT FK_USERINFO_TO_CHAT_1 FOREIGN KEY (
	email
)
REFERENCES USERINFO (
	email
);

ALTER TABLE FRIENDCREATE ADD CONSTRAINT FK_USERINFO_TO_FRIENDCREATE_1 FOREIGN KEY (
	email
)
REFERENCES USERINFO (
	email
);

ALTER TABLE FRIENDCREATE ADD CONSTRAINT FK_RELATIONSHIP_TO_FRIENDCREATE_1 FOREIGN KEY (
	relationno
)
REFERENCES RELATIONSHIP (
	relationno
);

ALTER TABLE HOMEINFO ADD CONSTRAINT FK_USERINFO_TO_HOMEINFO_1 FOREIGN KEY (
	email
)
REFERENCES USERINFO (
	email
);

INSERT INTO USERINFO
(EMAIL, PASSWORD, GENDER, JOINDATE, BIRTHDATE, 
USERNAME, VISITDATE, PWDATE, ADDR, COINNO, 
USERCONDITION) VALUES
('admin', 1234, 'W', SYSDATE, SYSDATE, 'admin', 
SYSDATE, SYSDATE, 'adminaddr', 100, 1);

SELECT * FROM DIARY;