DROP TABLE USERINFO PURGE;

CREATE TABLE USERINFO(	
	EMAIL VARCHAR2(100) PRIMARY KEY,
	PASSWORD VARCHAR2(100) NOT NULL,
	GENDER CHAR(2) CHECK(GENDER IN ('M','W')),
	JOINDATE DATE,
	BIRTHDATE DATE,
	USERNAME VARCHAR2(100),
	VISITDATE DATE,
	PWDATE DATE,
	ADDR VARCHAR2(4000),
	COINNO NUMBER(38),
	USERCONDITION NUMBER(2)
);

INSERT INTO USERINFO VALUES('admin', '1234', 'M', SYSDATE, '1994-05-02','관리자', SYSDATE, SYSDATE, '경기도 수원시', 10000, 0);
INSERT INTO USERINFO VALUES('admin2', '1234', 'M', SYSDATE, '1994-05-02','관리자2', SYSDATE, SYSDATE, '경기도 수원시', 10000, 1);

SELECT * FROM USERINFO;

DROP TABLE DIARY_FOLDER PURGE;
DROP SEQUENCE DIARY_FOLDERNOSEQ;
DROP SEQUENCE DIARY_FOLDERSEQ;

CREATE SEQUENCE DIARY_FOLDERNOSEQ;
CREATE SEQUENCE DIARY_FOLDERSEQ;
CREATE TABLE DIARY_FOLDER(
	FOLDERNO NUMBER PRIMARY KEY,
	EMAIL VARCHAR2(1000) NOT NULL,
	FOLDERNAME VARCHAR2(1000) NOT NULL,
	FOLDERSEQ NUMBER NOT NULL
);
ALTER TABLE DIARY_FOLDER ADD FOREIGN KEY (EMAIL) REFERENCES USERINFO(EMAIL);

INSERT INTO DIARY_FOLDER VALUES(DIARY_FOLDERNOSEQ.NEXTVAL,'admin','뚱s',DIARY_FOLDERSEQ.NEXTVAL);

SELECT * FROM DIARY_FOLDER;

DROP TABLE DIARY PURGE;
DROP SEQUENCE DIARYNOSEQ;

CREATE SEQUENCE DIARYNOSEQ;
CREATE TABLE DIARY(
	DIARYNO NUMBER PRIMARY KEY,
	FOLDERNO NUMBER NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(1000) NOT NULL,
	REGDATE DATE NOT NULL,
	FILEURL VARCHAR2(1000) NULL,
	PICURL VARCHAR2(1000) NULL,
	MAPLATI NUMBER NULL,
	MAPLONG NUMBER NULL,
	VIDEOURL VARCHAR2(1000) NULL,
	VIEWTIME NUMBER NOT NULL
);
ALTER TABLE DIARY ADD FOREIGN KEY (FOLDERNO) REFERENCES DIARY_FOLDER(FOLDERNO);

SELECT * FROM DIARY;

SELECT DIARYNO, FOLDERNO, TITLE, CONTENT, REGDATE, 
		FILEURL, PICURL, MAPLATI, MAPLONG, VIDEOURL, VIEWTIME
		FROM DIARY;

INSERT INTO DIARY 
VALUES(DIARYNOSEQ.NEXTVAL,'1','test title','test content',SYSDATE,'test fileurl','test picurl','1.1','2.2','test videourl',1);